using SDPX
using DoubleFloats
using JLD2
using Test

@testset "SDPX.jl" begin
    include("la_backend_regressions.jl")
    include("generic_la_backend.jl")
    include("correctness.jl")
    include("genericity.jl")
    include("extended_precision_blas.jl")
    include("sparse.jl")
    include("moi.jl")
    include("threads.jl")
    include("pipeline.jl")
    include("adaptive_parameter_policy.jl")
    include("preprocessing_regressions.jl")
    include("lp_regressions.jl")
    include("soc_regressions.jl")
    include("canonical_conic_problem.jl")
    include("problem_features.jl")
    include("auto_planner.jl")
    include("fixed_trace_benchmark_regressions.jl")
    include("soc_q3_kernel_regressions.jl")
    include("solver_regressions.jl")
    include("kkt_regressions.jl")
    include("kkt_sparse_backend.jl")
    include("sparse_sdp_kkt.jl")
    include("mixed_precision_kkt_regressions.jl")
    include("result_certificate.jl")
    include("infeasibility_diagnostics.jl")
    include("options_interface.jl")
    include("frontend_auto_options.jl")
    include("v041_architecture_regressions.jl")
    include("public_api.jl")
    include("performance_trace.jl")
    include("prepared_structure.jl")
    include("moi_regressions.jl")
    include("convex_regressions.jl")
    include("extended_blas_regressions.jl")
    include("bigfloat_kernel_regressions.jl")
    include("bigfloat_ownership_regressions.jl")
    include("bigfloat_sparse_schur_regressions.jl")
    include("schur_scheduler_regressions.jl")
    include("ingest_regressions.jl")
    include("spectrum_regressions.jl")
    include("extensions_regressions.jl")
    include("lp_sparse.jl")
    include("examples.jl")
    include("nullspace_reduction.jl")
    include("error_handling.jl")
    include("executed_diagnostics.jl")
    include("cli_bridge.jl")
    include("aqua.jl")
    include("shadowing_guard.jl")
    include("gates.jl")
end
