name = "SDPX"
uuid = "9c19f76d-03c5-4610-b403-7c8fdd8897fd"
authors = ["Yongjun Xu <yongjunx23@gmail.com>"]
version = "0.5.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MutableArithmetics = "d8a4904e-b15c-11e9-3269-09a3773c0cb0"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
AppleAccelerate = "13e28ba4-7ad8-5781-acae-3021b1ed3924"
BigFloatLinearAlgebra = "44d352a4-380e-4c6a-9c2a-31e5bfe329aa"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
MultiFloatLinearAlgebra = "642d9d30-8e28-45ca-9d81-256429ea358f"
MultiFloats = "bdf0d083-296b-4888-a5b6-7498122e68a5"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[extensions]
SDPXAppleAccelerateExt = "AppleAccelerate"
SDPXBigFloatLinearAlgebraExt = "BigFloatLinearAlgebra"
SDPXJLD2Ext = "JLD2"
SDPXGenericLinearAlgebraExt = "GenericLinearAlgebra"
SDPXLinearSolveExt = ["LinearSolve", "SciMLBase"]
SDPXMultiFloatLinearAlgebraExt = ["MultiFloats", "MultiFloatLinearAlgebra"]
SDPXMultiFloatsExt = "MultiFloats"

[compat]
AppleAccelerate = "0.7"
Aqua = "0.8"
BigFloatLinearAlgebra = "0.1"
Dates = "1"
Downloads = "1"
JLD2 = "0.4, 0.5, 0.6"
GenericLinearAlgebra = "0.3, 0.4"
JSON = "0.21, 1"
JuMP = "1"
LinearAlgebra = "1"
LinearSolve = "5"
MathOptInterface = "1.38"
MultiFloatLinearAlgebra = "0.1, 0.2"
MultiFloats = "3"
MutableArithmetics = "1"
Printf = "1"
Random = "1"
SciMLBase = "3"
SHA = "0.7"
Serialization = "1"
SparseArrays = "1"
StableRNGs = "1"
Statistics = "1"
Test = "1"
TOML = "1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MultiFloats = "bdf0d083-296b-4888-a5b6-7498122e68a5"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[targets]
test = ["Aqua", "Dates", "Downloads", "GenericLinearAlgebra", "JLD2", "JSON", "JuMP", "MultiFloats", "Random", "SHA", "StableRNGs", "Statistics", "Test", "TOML"]
