name = "twice_subtraction__alpha_0_quarter_mhalf__mu800__l80__a40__x3__maximize_c00"
subtraction = "twice_subtraction"
d = 4
N_mu = 800
N_a = 40
l_max = 80
N_x = 3
alpha_set = ["0", "-1/4", "-1/2"]
precompute_bits = 1024
solve_type = "Float64x4"
objective_sense = "max"
tolerance = "1e-12"
maximum_iterations = 500
time_limit_seconds = 43200.0
node_memory_gb = 128.0

[fixed_coefficients]

[objective]
c_0_0 = 1.0
