#!/bin/bash
# Static preflight for the canonical Stage-1 unchanged-hot-path A/B probe.
# No Julia, Pkg, SSH, or qsub is executed here.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
fail=0

check() {
  if ! "$@"; then
    echo "FAIL: $*"
    fail=1
  fi
}

echo "checking shell syntax"
for script in "$HERE"/*.sh "$HERE"/*.pbs; do
  check bash -n "$script"
done

echo "checking Python syntax"
check python3 -c \
  "import ast, pathlib; ast.parse(pathlib.Path('$HERE/analyze_ab.py').read_text())"
check python3 -c \
  "import ast, pathlib; ast.parse(pathlib.Path('$HERE/screen_summarize.py').read_text())"

echo "checking required files"
for file in README.md stage1_ab.pbs analyze_ab.py submit_stage1_ab.sh \
            submit_screen_parallel.sh screen_summarize.py static_check.sh; do
  check test -s "$HERE/$file"
done
check test -s "$HERE/aggregate_ab.py"

echo "checking PBS resource contract"
check grep -qF '#PBS -q sugon' "$HERE/stage1_ab.pbs"
check grep -qF '#PBS -l nodes=1:ppn=5' "$HERE/stage1_ab.pbs"
check grep -qF -- '-t 4' "$HERE/stage1_ab.pbs"
check grep -qF -- '--resource-class=regular' "$HERE/stage1_ab.pbs"
check grep -qF 'OPENBLAS_NUM_THREADS=1' "$HERE/stage1_ab.pbs"
check grep -qF 'JULIA_PKG_OFFLINE=true' "$HERE/stage1_ab.pbs"
check grep -qF '/usr/bin/time -v' "$HERE/stage1_ab.pbs"
check grep -qF 'already exists; refusing' "$HERE/stage1_ab.pbs"
check grep -qF 'NODE_NAME:?set NODE_NAME' "$HERE/stage1_ab.pbs"
check grep -qF 'AB_RUNNER_ROOT:?set AB_RUNNER_ROOT' "$HERE/stage1_ab.pbs"
check grep -qF 'baseline_tree_sha256' "$HERE/stage1_ab.pbs"
check grep -qF 'candidate_tree_sha256' "$HERE/stage1_ab.pbs"
check grep -qF 'runner_tree_sha256' "$HERE/stage1_ab.pbs"
check grep -qF 'baseline_source_sha256_subset' "$HERE/stage1_ab.pbs"
check grep -qF 'candidate_source_sha256_subset' "$HERE/stage1_ab.pbs"
check grep -qF 'AB_RUNNER_ROOT/analyze_ab.py' "$HERE/stage1_ab.pbs"
check grep -qF 'ab_runner_sha256' "$HERE/stage1_ab.pbs"

echo "checking A/B configuration"
check grep -qF 'run_generated_pathological.jl' "$HERE/stage1_ab.pbs"
check grep -qF -- '--arithmetic="$ARITHMETIC"' "$HERE/stage1_ab.pbs"
check grep -qF -- '--case-filter="$CASE_FILTER"' "$HERE/stage1_ab.pbs"
check grep -qF -- '--repetitions="$REPETITIONS"' "$HERE/stage1_ab.pbs"
check grep -qF -- '--warmup="$WARMUP"' "$HERE/stage1_ab.pbs"
check grep -qF 'lp_row_scaling,socp_many_tiny,sdp_hilbert' "$HERE/stage1_ab.pbs"
check grep -qF 'float64,float64x4' "$HERE/stage1_ab.pbs"
check grep -qF 'REPETITIONS:-' "$HERE/stage1_ab.pbs"
check grep -qF 'TIMING_BATCH_SIZE:-10' "$HERE/stage1_ab.pbs"
check grep -qF 'TIMED_BATCHES:-3' "$HERE/stage1_ab.pbs"
check grep -qF 'EXPECTED_REPETITIONS' "$HERE/stage1_ab.pbs"
check grep -qF 'timing_batch_size' "$HERE/stage1_ab.pbs"
check grep -qF 'timed_batches' "$HERE/stage1_ab.pbs"
check grep -qF 'ARM_ORDER:-baseline_first' "$HERE/stage1_ab.pbs"
check grep -qF 'arm_order' "$HERE/stage1_ab.pbs"
check grep -qF 'run_arm baseline' "$HERE/stage1_ab.pbs"
check grep -qF 'run_arm candidate' "$HERE/stage1_ab.pbs"
check grep -qF 'analyze_ab.py' "$HERE/stage1_ab.pbs"
check grep -qF 'arms.conf' "$HERE/stage1_ab.pbs"
check grep -qF 'SCREEN_MODE:-false' "$HERE/stage1_ab.pbs"
check grep -qF 'SCREEN_MODE requires a single-family CASE_FILTER' "$HERE/stage1_ab.pbs"
check grep -qF 'lp_row_scaling|socp_many_tiny|sdp_hilbert' "$HERE/stage1_ab.pbs"
check grep -qF 'TIMING_BATCH_SIZE:-5' "$HERE/stage1_ab.pbs"
check grep -qF -- '--screen' "$HERE/stage1_ab.pbs"
check grep -qF 'screen_mode=$SCREEN_MODE' "$HERE/stage1_ab.pbs"

echo "checking analysis gates"
check grep -qF '1.10' "$HERE/analyze_ab.py"
check grep -qF '0.05' "$HERE/analyze_ab.py"
check grep -qF 'SCREEN_CV_HARD_LIMIT = 0.20' "$HERE/analyze_ab.py"
check grep -qF -- '--screen' "$HERE/analyze_ab.py"
check grep -qF 'screen gate requires exact endpoint/iteration equality' "$HERE/analyze_ab.py"
check grep -qF 'WARN timing variance' "$HERE/analyze_ab.py"
check grep -qF 'screen_warn_cv' "$HERE/analyze_ab.py"
check grep -qF 'screen_endpoint_delta' "$HERE/analyze_ab.py"
check grep -qF 'input_sha256' "$HERE/analyze_ab.py"
check grep -qF 'objective_primal' "$HERE/analyze_ab.py"
check grep -qF 'certificate_residual' "$HERE/analyze_ab.py"
check grep -qF 'planned_backend' "$HERE/analyze_ab.py"
check grep -qF 'executed_backend' "$HERE/analyze_ab.py"
check grep -qF 'hostname' "$HERE/analyze_ab.py"
check grep -qF 'workspace_bytes' "$HERE/analyze_ab.py"
check grep -qF 'baseline_source_sha256_subset' "$HERE/analyze_ab.py"
check grep -qF 'candidate_source_sha256_subset' "$HERE/analyze_ab.py"
check grep -qF 'ab_provenance.txt' "$HERE/analyze_ab.py"
check grep -qF 'key[4] == 1' "$HERE/analyze_ab.py"
check grep -qF 'list(range(2, repetitions + 1))' "$HERE/analyze_ab.py"
check grep -qF 'timing_batch_size' "$HERE/analyze_ab.py"
check grep -qF 'timed_batches' "$HERE/analyze_ab.py"
check grep -qF 'SELF_TEST_TIMING_BATCH_SIZE' "$HERE/analyze_ab.py"
check grep -qF 'SELF_TEST_REPETITIONS' "$HERE/analyze_ab.py"
check grep -qF 'batch_index' "$HERE/analyze_ab.py"
check grep -qF '1000.0' "$HERE/analyze_ab.py"
check grep -qF -- '--self-test' "$HERE/analyze_ab.py"
check grep -qF 'AB_GATE_PASS' "$HERE/analyze_ab.py"
check grep -qF 'ab_report.csv' "$HERE/analyze_ab.py"

echo "checking aggregate tool"
check python3 -c \
  "import ast, pathlib; ast.parse(pathlib.Path('$HERE/aggregate_ab.py').read_text())"
check grep -qF 'AGGREGATE_GATE_PASS' "$HERE/aggregate_ab.py"
check grep -qF 'node_count' "$HERE/aggregate_ab.py"
check grep -qF 'median' "$HERE/aggregate_ab.py"
check grep -qF 'min' "$HERE/aggregate_ab.py"
check grep -qF 'max' "$HERE/aggregate_ab.py"
check grep -qF 'worst_cv' "$HERE/aggregate_ab.py"
check grep -qF 'AB_GATE_PASS' "$HERE/aggregate_ab.py"
check grep -qF 'ab_runner_sha256' "$HERE/aggregate_ab.py"
check grep -qF 'SELF_TEST_PASS' "$HERE/aggregate_ab.py"
check grep -qF -- '--self-test' "$HERE/aggregate_ab.py"
check grep -qF -- '--ordered' "$HERE/aggregate_ab.py"
check grep -qF -- '--legacy-baseline-first' "$HERE/aggregate_ab.py"
check grep -qF 'ORDERED_GATE_PASS' "$HERE/aggregate_ab.py"
check grep -qF 'timing_only' "$HERE/aggregate_ab.py"
check grep -qF 'non_timing' "$HERE/aggregate_ab.py"
check grep -qF 'baseline_commit' "$HERE/aggregate_ab.py"
check grep -qF 'timing_batch_size' "$HERE/aggregate_ab.py"

echo "checking submit script"
check grep -qF -- '--submit' "$HERE/submit_stage1_ab.sh"
check grep -qF 'qsub -v' "$HERE/submit_stage1_ab.sh"
check grep -qF 'nodes=$NODE_NAME:ppn=5' "$HERE/submit_stage1_ab.sh"
check grep -qF 'AB_RUNNER_ROOT:?set AB_RUNNER_ROOT' "$HERE/submit_stage1_ab.sh"
check grep -qF 'vars="$vars,AB_RUNNER_ROOT=$AB_RUNNER_ROOT"' "$HERE/submit_stage1_ab.sh"
check grep -qF 'TIMING_BATCH_SIZE' "$HERE/submit_stage1_ab.sh"
check grep -qF 'TIMED_BATCHES' "$HERE/submit_stage1_ab.sh"
check grep -qF 'must be a single token' "$HERE/submit_stage1_ab.sh"
check grep -qF 'CASE_FILTER' "$HERE/submit_stage1_ab.sh"
check grep -qF 'ARM_ORDER' "$HERE/submit_stage1_ab.sh"

echo "checking parallel screen submit script"
check grep -qF -- '--submit' "$HERE/submit_screen_parallel.sh"
check grep -qF 'qsub -N "$job_name" -v "$vars"' "$HERE/submit_screen_parallel.sh"
check grep -qF 'nodes=$node:ppn=5' "$HERE/submit_screen_parallel.sh"
check grep -qF 'three distinct healthy nodes' "$HERE/submit_screen_parallel.sh"
check grep -qF 'RESULT_ROOT_PREFIX' "$HERE/submit_screen_parallel.sh"
check grep -qF 'lp_row_scaling' "$HERE/submit_screen_parallel.sh"
check grep -qF 'socp_many_tiny' "$HERE/submit_screen_parallel.sh"
check grep -qF 'sdp_hilbert' "$HERE/submit_screen_parallel.sh"
check grep -qF 'SCREEN_MODE=true' "$HERE/submit_screen_parallel.sh"
check grep -qF 'TIMING_BATCH_SIZE:-5' "$HERE/submit_screen_parallel.sh"
check grep -qF 'TIMED_BATCHES:-3' "$HERE/submit_screen_parallel.sh"
check grep -qF -- '--screen' "$HERE/submit_screen_parallel.sh"
check grep -qF 'dry-run: re-run with --submit' "$HERE/submit_screen_parallel.sh"

echo "checking screen summary tool"
check grep -qF 'SCREEN_SUMMARY_PASS' "$HERE/screen_summarize.py"
check grep -qF 'SCREEN_SUMMARY_FAILED' "$HERE/screen_summarize.py"
check grep -qF 'screen_mode' "$HERE/screen_summarize.py"
check grep -qF '0.20' "$HERE/screen_summarize.py"
check grep -qF '1.10' "$HERE/screen_summarize.py"
check grep -qF 'lp_row_scaling' "$HERE/screen_summarize.py"
check grep -qF 'socp_many_tiny' "$HERE/screen_summarize.py"
check grep -qF 'sdp_hilbert' "$HERE/screen_summarize.py"
check grep -qF 'max_endpoint_norm' "$HERE/screen_summarize.py"
check grep -qF 'max_iteration_delta' "$HERE/screen_summarize.py"
check grep -qF -- '--legacy-screen-evidence' "$HERE/screen_summarize.py"
check grep -qF 'legacy_screen_fail_closed' "$HERE/screen_summarize.py"
check grep -qF 'legacy_screen_accepted' "$HERE/screen_summarize.py"
check grep -qF 'SELF_TEST_PASS' "$HERE/screen_summarize.py"
check grep -qF -- '--self-test' "$HERE/screen_summarize.py"

echo "checking policy documentation"
check grep -qF 'Cluster-only' "$HERE/README.md"
check grep -qF 'Do not' "$HERE/README.md"
check grep -qF 'full-tree' "$HERE/README.md"
check grep -qF 'subset' "$HERE/README.md"
check grep -qF 'workspace_bytes' "$HERE/README.md"
check grep -qF 'warmup' "$HERE/README.md"
check grep -qF 'batch sums' "$HERE/README.md"
check grep -qF 'TIMING_BATCH_SIZE' "$HERE/README.md"
check grep -qF 'TIMED_BATCHES' "$HERE/README.md"
check grep -qF 'AB_RUNNER_ROOT' "$HERE/README.md"
check grep -qF 'mom spool' "$HERE/README.md"
check grep -qF 'aggregate_ab.py' "$HERE/README.md"
check grep -qF 'ARM_ORDER' "$HERE/README.md"
check grep -qF 'Order-balanced screening' "$HERE/README.md"
check grep -qF -- '--legacy-baseline-first' "$HERE/README.md"
check grep -qF 'Development parallel screen' "$HERE/README.md"
check grep -qF 'release confirmation' "$HERE/README.md"
check grep -qF 'submit_screen_parallel.sh' "$HERE/README.md"
check grep -qF 'screen_summarize.py' "$HERE/README.md"
check grep -qF 'SCREEN_MODE' "$HERE/README.md"
check grep -qF 'CV warning band' "$HERE/README.md"
check grep -qF -- '--legacy-screen-evidence' "$HERE/README.md"

echo "running analyzer synthetic self-test"
check python3 "$HERE/analyze_ab.py" --self-test
echo "running aggregate synthetic self-test"
check python3 "$HERE/aggregate_ab.py" --self-test
echo "running screen summary synthetic self-test"
check python3 "$HERE/screen_summarize.py" --self-test

if [ "$fail" -ne 0 ]; then
  echo "static check FAILED"
  exit 1
fi
echo "static check PASSED"
