#!/usr/bin/env python3
"""Build the four control-arm fixtures for check_reconstruction_controls.sh.

    q02_control_fixtures.py <CLEAN_MANIFEST> <WORKDIR> <SDPX_REPO_PATH>

WHY THIS IS A SEPARATE FILE AND NOT AN INLINE HEREDOC. It was an inline
`python3 - <<'PY'` block inside a script that is itself generated by a heredoc in
another tool, and the two `PY` delimiters collided: the inner terminator closed the
outer block and the rest of the script executed as shell. A fixture generator that
can silently bisect the script that calls it is not worth the file it saves.

WHAT IT GUARANTEES, and each of these is a way the earlier version was wrong:

  * every arm's fixture is built from the CLEAN manifest, in one process, so no arm
    can inherit another arm's perturbation;
  * `rewrite_fields` asserts the entry AND the field exist, so a typo produces a
    loud failure rather than an arm that perturbs nothing and "passes";
  * the sha256 of each fixture is printed, so a reader can see they are independent;
  * the symmetric arms put the SAME phantom entry on both sides and differ in
    exactly ONE field.

Outputs, in WORKDIR:
    arm_c_live.txt / arm_c_compared.txt        presence: phantom on the live side only
    arm_d_live.txt / arm_d_compared.txt        git-tree-sha1 differs, nothing else
    arm_e_live.txt / arm_e_compared.txt        uuid differs, nothing else
    arm_f_live.txt / arm_f_compared.txt        version differs, nothing else
"""

import hashlib
import os
import re
import sys

# The phantom's uuid is a REAL stdlib uuid (LinearAlgebra) on purpose. The checker's
# Q02_PREP section 6 gate refuses any sha-less entry that is neither first-party nor
# a stdlib, and an invented uuid tripped THAT gate before the dependency-set diff
# could run -- the arm failed for an unrelated reason. Using a real stdlib uuid
# keeps the fixture inside the recipe's rules so the arm exercises the diff.
UUID_A = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"   # LinearAlgebra (stdlib)
UUID_B = "8f399da3-3557-5675-b5ff-fb832c97cbdb"   # Libdl (stdlib)
VERSION_A = "9.9.9"
VERSION_B = "9.9.8"
SHA_A = "0000000000000000000000000000000000000001"
SHA_B = "0000000000000000000000000000000000000002"
ENTRY = "Q02ControlPhantom"


def sha256_text(text):
    return hashlib.sha256(text.encode()).hexdigest()


def inject(text, block):
    """Insert a `[[deps.X]]` block after the first existing dep block."""
    match = re.search(r"^\[\[deps\.[^\]]+\]\]$", text, re.M)
    if match is None:
        return text.rstrip() + "\n\n" + block.strip() + "\n"
    end = text.find("\n[[deps.", match.end())
    if end < 0:
        end = len(text)
    return text[:end] + "\n" + block.strip() + "\n" + text[end:]


def rewrite_fields(text, entry, **changes):
    """Replace field values inside ONE `[[deps.<entry>]]` block.

    Asserts the entry and every field exist. A miss is an error rather than a
    silent no-op, because a no-op fixture is a control arm that tests nothing and
    still reports FAIL for the wrong reason.
    """
    match = re.search(r"^\[\[deps\." + re.escape(entry) + r"\]\]$", text, re.M)
    assert match, f"entry [[deps.{entry}]] not found in the manifest"
    nxt = text.find("\n[[deps.", match.end())
    nxt = len(text) if nxt < 0 else nxt
    block = text[match.end():nxt]
    for field, value in changes.items():
        pattern = re.compile(r'^(' + re.escape(field) + r'\s*=\s*)"[^"]*"$', re.M)
        assert pattern.search(block), f"field {field} not found under [[deps.{entry}]]"
        block = pattern.sub(lambda m: m.group(1) + '"' + value + '"', block, count=1)
    return text[:match.end()] + block + text[nxt:]


def phantom(uuid, version, tree_sha1=None, path=None):
    lines = [f"[[deps.{ENTRY}]]"]
    if tree_sha1:
        lines.append(f'git-tree-sha1 = "{tree_sha1}"')
    if path:
        lines.append(f'path = "{path}"')
    lines.append(f'uuid = "{uuid}"')
    lines.append(f'version = "{version}"')
    return "\n" + "\n".join(lines) + "\n"


def build_asymmetric(env_dir, out_dir):
    """Arm (c): a genuine ONE-SIDED dependency difference, produced by the resolver.

    THE TAUTOLOGY THIS REPLACES, twice over. The reconstruction COPIES
    `rebuild-env` -- including its `Manifest.toml` -- and then calls
    `Pkg.instantiate()`. So:

      * an entry INJECTED into that copied Manifest lands on BOTH sides: the first
        arm (c) injected a `path`-based phantom, `Pkg.instantiate()` preserved it
        verbatim, the checker reported `recorded entries 61  reconstructed entries
        61`, `diff_dep_sets` compared a fixture with itself, and the arm PASSED
        when it was required to FAIL. A control whose two sides move together can
        only ever agree.

      * an entry ADDED TO THE PROJECT that is ALREADY in the Manifest also changes
        nothing: the second attempt added `GenericLinearAlgebra` to
        `rebuild-env/Project.toml`, but `GenericLinearAlgebra` is already resolved
        in the manifest as a transitive dependency of SDPX, so the resolved set was
        unchanged again (`60 vs 60`) and the arm passed again.

    What actually works is a REMOVAL from the manifest of something the resolver
    must put back. `QDLDL` is used because:

      * it is a DIRECT dependency of `rebuild-env/Project.toml`, so `instantiate()`
        re-resolves it and re-adds it to the manifest;
      * it is NOT a dependency of SDPX (`SDPX.deps` is Dates, LinearAlgebra,
        MathOptInterface, MutableArithmetics, SHA, Serialization, SparseArrays,
        TOML), so its removal leaves the rest of the graph intact;
      * it is already installed in the depot, so the arm needs no network.

    The recorded side is therefore the manifest WITH `QDLDL` and the reconstruction
    resolves a manifest WITHOUT it recorded -- the difference appears on the
    reconstructed side, which is the shape the presence comparison exists to catch.

    Every candidate is CHECKED rather than assumed: the entry must be present in
    the manifest, be named in the project's `[deps]`, and be depended on by nothing.
    A miss is an error, because a silent miss makes the arm a tautology again --
    which has now happened twice.
    """
    project_path = os.path.join(env_dir, "Project.toml")
    manifest_path = os.path.join(env_dir, "Manifest.toml")
    with open(manifest_path, encoding="utf-8") as handle:
        manifest = handle.read()
    with open(project_path, encoding="utf-8") as handle:
        project = handle.read()

    project_deps = set(re.findall(r"^([A-Za-z0-9_]+)\s*=\s*\"", project, re.M))
    blocks = dict(re.findall(r"^\[\[deps\.([^\]]+)\]\]\n(.*?)(?=\n\[\[|\Z)",
                             manifest, re.S | re.M))
    assert blocks, "no dependency blocks parsed from the manifest -- refusing to guess"

    def dependents(name):
        out = []
        for other, block in blocks.items():
            if other == name:
                continue
            m = re.search(r'^deps\s*=\s*\[(.*?)\]', block, re.M)
            if m and name in [s.strip().strip('"') for s in m.group(1).split(",")]:
                out.append(other)
        return out

    # Preference order: the project's own declared deps, minus anything the
    # manifest graph would drag back in for another reason.
    # The three first-party packages are EXCLUDED: they are re-added by
    # `Pkg.develop(path=...)` at a different layer, so removing one would exercise
    # a different mechanism than the Manifest resolution this arm is about.
    first_party = {"SDPX", "MultiFloatLinearAlgebra", "BigFloatLinearAlgebra"}
    candidates = [n for n in sorted(project_deps)
                  if n in blocks and n not in first_party and not dependents(n)]
    assert candidates, ("no removable entry found: every project dependency is either "
                        "absent from the manifest or depended on by another entry")
    victim = candidates[0]

    removed = re.sub(r"^\[\[deps\." + re.escape(victim) + r"\]\]\n.*?(?=\n\[\[|\Z)",
                     "", manifest, flags=re.S | re.M).replace("\n\n\n", "\n\n")
    n_before = len(re.findall(r"^\[\[deps\.", manifest, re.M))
    n_after = len(re.findall(r"^\[\[deps\.", removed, re.M))
    assert n_after == n_before - 1, f"removal of {victim} changed {n_before} -> {n_after}"

    # Written to `out_dir`, NOT into the env copy: the checker is handed this path
    # via `--manifest`, and a fixture written inside the env directory is one more
    # thing a later `cp -r` or cleanup can move. Two explicit arguments cost nothing
    # and remove the ambiguity that produced "Manifest not found".
    recorded = os.path.join(out_dir, "arm_c_recorded.txt")
    os.makedirs(out_dir, exist_ok=True)
    with open(recorded, "w", encoding="utf-8") as handle:
        handle.write(removed)
    print(f"  arm c: removed [[deps.{victim}]] from the RECORDED manifest "
          f"({n_before} -> {n_after} entries)")
    print(f"         {victim} is declared in the project's [deps] and depended on by "
          f"nothing, so Pkg.instantiate() must re-resolve and re-add it -- the "
          f"reconstructed side is then the one with an extra entry")
    print(f"         recorded: {recorded}  sha256 {sha256_text(removed)[:12]}")
    print(f"         project unchanged: {project_path}  (the live rebuild-env is NOT touched)")
    return 0


def main(argv):
    if len(argv) > 1 and argv[1] == "--asymmetric":
        return build_asymmetric(argv[2], argv[3])
    clean_path, work, sdpx = argv[1], argv[2], argv[3]
    with open(clean_path, encoding="utf-8") as handle:
        clean = handle.read()
    os.makedirs(work, exist_ok=True)

    # (c) PRESENCE. The live (recorded) side carries the phantom; the compared side
    #     does not. The failure must be a pure presence difference, so the phantom's
    #     OTHER fields are deliberately identical on both sides -- an earlier
    #     version used a different uuid here, which made the arm report TWO
    #     differences (a presence one AND a uuid one) and the arm's own
    #     reason-check caught it. A presence arm that also perturbs a field is not
    #     a control for presence.
    arm_c_live = inject(clean, phantom(UUID_A, VERSION_A, path=sdpx))
    arm_c_compared = inject(clean, phantom(UUID_A, VERSION_A, path=sdpx))

    # (d) TREE_SHA1. Both sides carry the entry with the same uuid and version;
    #     only `git-tree-sha1` differs. The recorded side names SHA_A.
    live_d = inject(clean, phantom(UUID_A, VERSION_A, tree_sha1=SHA_A, path=sdpx))
    cmp_d = inject(clean, phantom(UUID_A, VERSION_A, tree_sha1=SHA_B, path=sdpx))

    # (e) UUID. Same version and sha (none), only `uuid` differs.
    live_e = inject(clean, phantom(UUID_A, VERSION_A, path=sdpx))
    cmp_e = inject(clean, phantom(UUID_B, VERSION_A, path=sdpx))

    # (f) VERSION. Same uuid, only `version` differs.
    live_f = inject(clean, phantom(UUID_A, VERSION_A, path=sdpx))
    cmp_f = inject(clean, phantom(UUID_A, VERSION_B, path=sdpx))

    written = []
    for key, live_text, cmp_text in (("c", arm_c_live, arm_c_compared),
                                     ("d", live_d, cmp_d),
                                     ("e", live_e, cmp_e),
                                     ("f", live_f, cmp_f)):
        live_path = os.path.join(work, f"arm_{key}_live.txt")
        cmp_path = os.path.join(work, f"arm_{key}_compared.txt")
        with open(live_path, "w", encoding="utf-8") as handle:
            handle.write(live_text)
        with open(cmp_path, "w", encoding="utf-8") as handle:
            handle.write(cmp_text)
        written.append((key, live_path, cmp_path, live_text, cmp_text))

    for key, live_path, cmp_path, live_text, cmp_text in written:
        n_live = len(re.findall(r"^\[\[deps\.", live_text, re.M))
        n_cmp = len(re.findall(r"^\[\[deps\.", cmp_text, re.M))
        print(f"  arm {key}: live {n_live} entries sha256 {sha256_text(live_text)[:12]}  "
              f"compared {n_cmp} entries sha256 {sha256_text(cmp_text)[:12]}")
    print(f"  all four fixtures built independently from the clean manifest "
          f"(sha256 {sha256_text(clean)[:12]})")

    # The symmetric arms must differ from their partner in EXACTLY the target
    # field. This is asserted here rather than trusted, because "one field differs"
    # is the property that makes (d)/(e)/(f) controls for that field.
    import difflib
    for key, field in (("d", "git-tree-sha1"), ("e", "uuid"), ("f", "version")):
        live_text = dict((k, (a, b)) for k, a, b, *_ in written)[key][0]
        cmp_text = dict((k, (a, b)) for k, a, b, *_ in written)[key][1]
        live_text = open(dict((k, a) for k, a, _, _, _ in written)[key],
                         encoding="utf-8").read()
        cmp_text = open(dict((k, b) for k, _, b, _, _ in written)[key],
                        encoding="utf-8").read()
        changed = [line for line in difflib.unified_diff(live_text.splitlines(),
                                                         cmp_text.splitlines(), lineterm="")
                   if line.startswith(("+", "-")) and not line.startswith(("+++", "---"))]
        non_field = [line for line in changed if field not in line]
        status = "OK" if (len(changed) == 2 and not non_field) else "BAD"
        print(f"  arm {key} differs from its partner in exactly one field ({field}): "
              f"{status} changed_lines={len(changed)}")
        if status == "BAD":
            for line in changed:
                print(f"      {line}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
