#!/usr/bin/env python3
"""Record every driver run's testset counts, per task, into one file.

    record_run_history.py [WORKSPACE] [-o RUN_HISTORY.md]

WHY. A worker debugging its own code can reach a green run by fixing the code or by
weakening the test, and the final log alone cannot tell them apart. S07 went through
eleven runs; B02's driver log was rewritten in place. Recording the counts *while the
runs happen* gives every eventual green run a documented BEFORE, and the assertion
count is the discriminator: green with FEWER assertions than an earlier failing run
means something was removed.

Written as a script because the parser has now been hand-written three times and got
the column count wrong twice. `Test Summary` tables have a variable column set —
`Pass Total`, `Pass Fail Total`, `Pass Error Total`, `Pass Fail Error Total`,
`Broken Total` — so the columns are read from the header line, never assumed.
"""

import argparse
import glob
import os
import re
import sys

SUMMARY_LINE = re.compile(r"^(.*?)\s*\|\s*(.*?)\s*(\d+m[\d.]+s|[\d.]+s)\s*$")


def parse(path):
    """[(testset name, {column: value})] from one Julia Test Summary log."""
    rows = []
    header = None
    with open(path, encoding="utf-8", errors="replace") as handle:
        for line in handle:
            line = line.rstrip("\n")
            if line.startswith("Test Summary:"):
                header = [c.strip() for c in line.split("|", 1)[1].split()
                          if c.strip() != "Time"]
                continue
            m = SUMMARY_LINE.match(line)
            if not m or not header:
                continue
            nums = m.group(2).split()
            if len(nums) != len(header) or not all(n.isdigit() for n in nums):
                continue
            rows.append((m.group(1).strip(), dict(zip(header, (int(n) for n in nums)))))
            header = None
    return rows


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("workspace", nargs="?", default=os.getcwd())
    ap.add_argument("-o", "--out", default=None)
    args = ap.parse_args(argv)

    reports = os.path.join(args.workspace, "rebuild-reports")
    out_path = args.out or os.path.join(reports, "RUN_HISTORY.md")

    body = [
        "# DRIVER RUN HISTORY",
        "",
        "Generated by `SDPX.jl/scripts/rebuild/record_run_history.py`. Do not edit by",
        "hand — re-run it.",
        "",
        "Recorded so an eventual green run has a documented BEFORE. A worker debugging",
        "its own code can reach green by fixing the code or by weakening the test, and",
        "the final log alone cannot tell them apart. The assertion count is the",
        "discriminator: green with FEWER assertions than an earlier failing run means",
        "something was removed. Columns are read from each log's own header, because",
        "`Test Summary` tables have a variable column set.",
        "",
    ]
    tasks = sorted(d for d in os.listdir(reports)
                   if os.path.isdir(os.path.join(reports, d)) and d[0].isalpha())
    total_rows = 0
    for task in tasks:
        logs = sorted(glob.glob(os.path.join(reports, task, "*.log")))
        if not logs:
            continue
        body.append(f"## {task}")
        for path in logs:
            rows = parse(path)
            name = os.path.basename(path)
            if not rows:
                body.append(f"  {name:30s} (no Test Summary line — empty, crashed, or still running)")
                continue
            for testset, cols in rows:
                rendered = " ".join(f"{k}={v}" for k, v in cols.items())
                body.append(f"  {name:30s} {testset[:44]:44s} {rendered}")
                total_rows += 1
        body.append("")

    with open(out_path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(body) + "\n")
    print(f"wrote {out_path}")
    print(f"tasks={len(tasks)} summary_rows={total_rows}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
