#=
# SymmetryReduction (Phase 7) - user-provided symmetry generators.
#
# First, correct step of the symmetry-reduction layer: given user-provided
# permutation generators, compute the group orbits, verify invariance of a
# candidate matrix, derive the diagonal-action pair orbits (the commutant
# structure that a group-invariant matrix is constant on), and provide a
# reversible reduction/reconstruction permutation. The full irrep
# block-diagonalization is the next step on top of this foundation.
#
# The pair-action orbit decomposition is the key invariant: a matrix A is
# group-invariant exactly when it is constant on each pair orbit under the
# diagonal action sigma*(i,j) = (sigma(i), sigma(j)).
=#

"""A symmetry group on `n` indices generated by 1-based permutation vectors."""
struct SymmetryGroup
    n::Int
    generators::Vector{Vector{Int}}
end

function SymmetryGroup(generators::Vector{<:AbstractVector{<:Integer}}, n::Int)
    for sigma in generators
        length(sigma) == n || throw(ArgumentError("generator length must be $n"))
        sort(collect(sigma)) == collect(1:n) || throw(ArgumentError("generator must be a permutation of 1:$n"))
    end
    return SymmetryGroup(n, Vector{Int}.(generators))
end

"""Apply a permutation vector `sigma` (image map) to `x` in place (P*x)."""
function permute!(destination::AbstractVector{T}, x::AbstractVector{T}, sigma::Vector{Int}) where {T}
    for i in eachindex(sigma)
        destination[i] = x[sigma[i]]
    end
    return destination
end

"""Orbit of an index under the group generated by `generators`."""
function orbit(g::SymmetryGroup, start::Int)
    seen = Set{Int}([start])
    frontier = [start]
    while !isempty(frontier)
        current = popfirst!(frontier)
        for sigma in g.generators
            next_index = sigma[current]
            if !(next_index in seen)
                push!(seen, next_index)
                push!(frontier, next_index)
            end
            preimage = findfirst(==(current), sigma)
            if preimage !== nothing && !(preimage in seen)
                push!(seen, preimage)
                push!(frontier, preimage)
            end
        end
    end
    return sort!(collect(seen))
end

"""Partition of `1:n` into the orbits of the group action."""
function group_orbits(g::SymmetryGroup)
    assigned = Set{Int}()
    orbits = Vector{Vector{Int}}()
    for i in 1:g.n
        i in assigned && continue
        orb = orbit(g, i)
        union!(assigned, orb)
        push!(orbits, orb)
    end
    return orbits
end

" check whether a matrix is invariant under every generator. "
function is_matrix_invariant(A::AbstractMatrix, g::SymmetryGroup)
    size(A) == (g.n, g.n) || return false
    for sigma in g.generators
        @inbounds for i in 1:g.n
            for j in 1:g.n
                A[sigma[i], sigma[j]] == A[i, j] || return false
            end
        end
    end
    return true
end

"""A reduction permutation ordering indices by orbit (block grouping)."""
function reduction_permutation(g::SymmetryGroup)
    perm = Int[]
    for orb in group_orbits(g)
        append!(perm, orb)
    end
    return perm
end

"""Inverse permutation (for reconstruction)."""
function inverse_permutation(perm::Vector{Int})
    n = length(perm)
    inverse = Vector{Int}(undef, n)
    for (k, v) in enumerate(perm)
        inverse[v] = k
    end
    return inverse
end

"""Reconstruct a vector in original coordinates from a reduced vector."""
function reconstruct(reduced::AbstractVector{T}, perm::Vector{Int}) where {T}
    n = length(perm)
    length(reduced) == n || throw(DimensionMismatch)
    original = Vector{T}(undef, n)
    for (k, v) in enumerate(perm)
        original[v] = reduced[k]
    end
    return original
end