#=
# SymmetryReduction (Phase 7) - user-provided symmetry generators.
#
# First, correct step of the symmetry-reduction layer: given user-provided
# permutation generators, compute the group orbits, verify invariance of a
# candidate matrix, derive the diagonal-action pair orbits (the commutant
# structure that a group-invariant matrix is constant on), and provide a
# reversible reduction/reconstruction permutation. The full irrep
# block-diagonalization is the next step on top of this foundation.
#
# The pair-action orbit decomposition is the key invariant: a matrix A is
# group-invariant exactly when it is constant on each pair orbit under the
# diagonal action sigma*(i,j) = (sigma(i), sigma(j)).
=#

"""A symmetry group on `n` indices generated by 1-based permutation vectors."""
struct SymmetryGroup
    n::Int
    generators::Vector{Vector{Int}}
end

function SymmetryGroup(generators::Vector{<:AbstractVector{<:Integer}}, n::Int)
    for sigma in generators
        length(sigma) == n || throw(ArgumentError("generator length must be $n"))
        sort(collect(sigma)) == collect(1:n) || throw(ArgumentError("generator must be a permutation of 1:$n"))
    end
    return SymmetryGroup(n, Vector{Int}.(generators))
end

"""Apply a permutation vector `sigma` (image map) to `x` in place (P*x)."""
function permute!(destination::AbstractVector{T}, x::AbstractVector{T}, sigma::Vector{Int}) where {T}
    for i in eachindex(sigma)
        destination[i] = x[sigma[i]]
    end
    return destination
end

"""Orbit of an index under the group generated by `generators`."""
function orbit(g::SymmetryGroup, start::Int)
    seen = Set{Int}([start])
    frontier = [start]
    while !isempty(frontier)
        current = popfirst!(frontier)
        for sigma in g.generators
            next_index = sigma[current]
            if !(next_index in seen)
                push!(seen, next_index)
                push!(frontier, next_index)
            end
            preimage = findfirst(==(current), sigma)
            if preimage !== nothing && !(preimage in seen)
                push!(seen, preimage)
                push!(frontier, preimage)
            end
        end
    end
    return sort!(collect(seen))
end

"""Partition of `1:n` into the orbits of the group action."""
function group_orbits(g::SymmetryGroup)
    assigned = Set{Int}()
    orbits = Vector{Vector{Int}}()
    for i in 1:g.n
        i in assigned && continue
        orb = orbit(g, i)
        union!(assigned, orb)
        push!(orbits, orb)
    end
    return orbits
end

" check whether a matrix is invariant under every generator. "
function is_matrix_invariant(A::AbstractMatrix, g::SymmetryGroup)
    size(A) == (g.n, g.n) || return false
    for sigma in g.generators
        @inbounds for i in 1:g.n
            for j in 1:g.n
                A[sigma[i], sigma[j]] == A[i, j] || return false
            end
        end
    end
    return true
end

"""A reduction permutation ordering indices by orbit (block grouping)."""
function reduction_permutation(g::SymmetryGroup)
    perm = Int[]
    for orb in group_orbits(g)
        append!(perm, orb)
    end
    return perm
end

"""Inverse permutation (for reconstruction)."""
function inverse_permutation(perm::Vector{Int})
    n = length(perm)
    inverse = Vector{Int}(undef, n)
    for (k, v) in enumerate(perm)
        inverse[v] = k
    end
    return inverse
end

"""Reconstruct a vector in original coordinates from a reduced vector."""
function reconstruct(reduced::AbstractVector{T}, perm::Vector{Int}) where {T}
    n = length(perm)
    length(reduced) == n || throw(DimensionMismatch)
    original = Vector{T}(undef, n)
    for (k, v) in enumerate(perm)
        original[v] = reduced[k]
    end
    return original
end

"""Orbits of the diagonal pair action `sigma*(i,j)=(sigma(i),sigma(j))`.
A group-invariant matrix is exactly constant on each pair orbit."""
function pair_orbits(g::SymmetryGroup)
    seen = Set{Tuple{Int,Int}}()
    orbits = Vector{Vector{Tuple{Int,Int}}}()
    for i in 1:g.n, j in 1:g.n
        (i, j) in seen && continue
        orb = Set([(i, j)])
        frontier = [(i, j)]
        while !isempty(frontier)
            (a, b) = popfirst!(frontier)
            for sigma in g.generators
                nxt = (sigma[a], sigma[b])
                nxt in orb || (push!(orb, nxt); push!(frontier, nxt))
            end
        end
        union!(seen, orb)
        push!(orbits, sort!(collect(orb)))
    end
    return orbits
end

"""Whether `A` is constant on every diagonal pair orbit (the commutant
condition, equivalent to group invariance)."""
function is_constant_on_pair_orbits(A::AbstractMatrix, orbits::Vector{<:AbstractVector{<:Tuple{Int,Int}}})
    for orb in orbits
        reference = A[first(orb)...]
        for pair in orb
            A[pair...] == reference || return false
        end
    end
    return true
end

"""Orthogonal block-diagonalizing basis for disjoint transposition swaps.
Each pair `(i,j)` is reduced by the Hadamard-like basis (sum/difference of the
two coordinates); untouched indices keep the standard basis.  For any matrix
invariant under these swaps, `Q' A Q` is block-diagonal."""
function transposition_block_basis(pairs::Vector{<:Tuple{Int,Int}}, n::Int)
    # Column ordering: (1) sum components of every swap, (2) unpaired indices,
    # (3) difference components. This groups the coupled trivial components
    # into one leading block so Q' A Q is block-diagonal for invariant A.
    Q = zeros(Float64, n, n)
    column = 1
    for (i, j) in pairs
        i != j || continue
        Q[i, column] = 1 / sqrt(2.0)
        Q[j, column] = 1 / sqrt(2.0)
        column += 1
    end
    used = falses(n)
    for (i, j) in pairs
        used[i] = true
        used[j] = true
    end
    for i in 1:n
        used[i] && continue
        Q[i, column] = 1.0
        column += 1
    end
    for (i, j) in pairs
        i != j || continue
        Q[i, column] = 1 / sqrt(2.0)
        Q[j, column] = -1 / sqrt(2.0)
        column += 1
    end
    column == n + 1 || error("inconsistent pair set")
    return Q
end

"""Conjugate a matrix to block-diagonal form: `Q' A Q`."""
function block_diagonalize(A::AbstractMatrix, Q::AbstractMatrix)
    return transpose(Q) * A * Q
end

"""Whether `A` is (numerically) block-diagonal with the given block sizes."""
function is_block_diagonal(A::AbstractMatrix, block_sizes::Vector{Int};
    tol::Real=1e-10)
    n = size(A, 1)
    sum(block_sizes) == n || return false
    block_of = zeros(Int, n)
    index = 1
    for (block, size) in enumerate(block_sizes)
        for _ in 1:size
            block_of[index] = block
            index += 1
        end
    end
    @inbounds for i in 1:n, j in 1:n
        if block_of[i] != block_of[j] && abs(A[i, j]) > tol
            return false
        end
    end
    return true
end

"""Block sizes produced by [`transposition_block_basis`]: one leading block
holding all sum components plus unpaired indices, then a 1x1 block per swap."""
function transposition_block_sizes(pairs::Vector{<:Tuple{Int,Int}}, n::Int)
    effective = [p for p in pairs if p[1] != p[2]]
    used = Set{Int}()
    for (i, j) in effective
        push!(used, i)
        push!(used, j)
    end
    unpaired = count(i -> !(i in used), 1:n)
    leading = length(effective) + unpaired
    return vcat([leading], ones(Int, length(effective)))
end
